// llama_attention_full head 31's P @ V tile, verbatim -- the one matmul the FPGA gets 1 ulp wrong
// (0xbc18 where spike and the model give 0xbc17, at row 31 col 13). M=32 K=32 N=64: I=2 J=4 Kt=2.
//
// Not a bisection rung: a REPRODUCER. Its data is a spike dump of the real tile, not the ladder's
// seeded operands, so it is regenerated by gen/gen_pv_repro.py, not gen_mx_ladder.py.
//
// Generated data: data/mx_ladder_mxl20.h. Driver: src/mx_ladder.c.
#define LADDER_HEADER "mx_ladder_mxl20.h"
#define LADDER_KIND   KIND_PLAIN
#include "mx_ladder.c"
